config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :trashes
  get 'users/index'

  resources :rooms
  resources :courses
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  get 'users', to: 'users#index', as: 'users'
  post 'pub_trash', to: 'trashes#pub_trash', as: 'pub_trash'
  get 'pub_trash', to: 'trashes#pub_trash', as: 'published_trash'
  # get 'user/:id', to: 'users#show', as: 'user'
  # get 'user/edit/:id', to: 'users#edit', as: 'user_edit'

  resources :user, :controller => "users"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  # Home pages
  get 'home/tarefas', to: 'home#tarefas'

  # Swap tasks

  get '/trashes/swap/:id', to: 'trashes#swap_trash', as: 'swap_trash' # Swap trash
  get '/notifications/send/:id/:table', to: 'notifications#new', as: 'send_notification'
  get '/notifications/:id', to: 'notifications#show', as: 'notification'
  get '/notifications', to: 'notifications#index', as: 'notifications'
  post '/notifications', to: 'notifications#create'
  delete '/notifications/:id', to: 'notifications#destroy'
  post '/notifications/response', to: 'notifications#notification_response'
  get '/gerar_tabela', to: 'trashes#generate_trash_table', as: 'generate_trash_table'

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  has_paper_trail
  acts_as_paranoid


  validates :from, uniqueness: {scope: [:table_type, :is_response], unless: :is_response, message: 'Não é permitido enviar mais de uma solicitação de troca para uma mesma tabela.'}

  def sender
    @sender = User.find(self.from)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :destroy]
  before_action :set_paper_trail_whodunnit

  def index
    @notifications = current_user.notifications
    if params[:q]
      @notification = Notification.find(params[:q])
    end
  end

  def new
    @notification = Notification.new
    id = params[:id]
    table = params[:table]
    @trash = Trash.find(id)
    @user = current_user
    @notification.subject = 'Solicitação de troca em tabela de tarefa.'
    @notification.user_id = @trash.user_id
    @notification.from = @user.id
    @notification.task_id = id
    @notification.read = false
    @notification.is_response = false
    @notification.table_type = table
  end

  def show
    if @notification.user_id == current_user.id
      @notification.read = true
      @notification.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html {redirect_to home_tarefas_url, notice: 'Sua solicitação de troca foi enviada ao reseidente selecionado. Você será informado quando ele aceitar ou recusar a troca.'}
        format.json {head :no_content}
      else
        format.html { redirect_to home_tarefas_url, alert: 'Não é permitido enviar mais de uma solicitação de troca para uma mesma tabela.' }
        format.json {render json: @notification.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    unless @notification.is_response
      task_id = @notification.task_id
      @trash = Trash.find(task_id)
      @trash.deny_request(@notification, false)
    end
    @notification.destroy
    respond_to do |format|
      format.html {redirect_to notifications_path, notice: 'Notificação apagada com sucesso.'}
      format.json {head :no_content}
    end
  end

  def notification_response
    @notification = Notification.find(params[:id])
    @resp = params[:resp]
    @task_id = @notification.task_id
    if @notification.table_type == 'trash'
      @trash = Trash.find(@task_id)
      @trash.swap(@notification, @resp)
      respond_to do |format|
        format.html { redirect_to notifications_path, notice: 'Troca realizada com sucesso.'}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params.require(:notification).permit(:from, :task_type, :description, :subject, :task_id, :read, :user_id, :trash_id, :trash_user_id, :table_type)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<% content_for :full_box do %>flag
<% end %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h2 class="box-title">Enviar solicitação</h2>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= simple_form_for(@notification) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <div class="row">
            <div class="col-md-12">
              <%= f.input :user_id, as: :hidden %>
              <strong>Destinatário:</strong> <%= @notification.user.name %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <strong>Tabela:</strong> <%= t('activerecord.models.'+@notification.table_type) %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12">
              <%= f.input :subject %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.input :table_type, as: :hidden %>
              <%= f.input :task_id, as: :hidden %>
              <%= f.input :from, as: :hidden %>
              <%= f.input :read, as: :hidden %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.input :description, as: :text %>
            </div>
          </div>

        </div>

        <div class="form-actions">
          <%= f.submit 'Enviar solicitação', class: 'btn btn-primary', data: {confirm: 'Tem certeza?'} %>
        </div>
    <% end %>
  </div>
  <!-- /.box-body -->
</div>
<!-- /. box -->
<%= console %>

app/views/notifications/_list.html.erb
<!--
REMEMBER!

-- javascript para substituir conteudo da div que contém a tabela
    * Ao clicar numa notificação, os detalhes devem ser abertos no lugar da tabela.
    * Ao clicar no menu do lado, deve mostrar novamente a tabela.
 -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Notificações</h3>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <div class="table-responsive mailbox-messages">
      <table id="table-notifications" class="table table-hover table-bordered">
        <thead>
        <tr>
          <th class="col-md-1">Selecionar</th>
          <th>Remetente</th>
          <th>Assunto</th>
          <th>Tabela</th>
          <th>Ação</th>
        </tr>
        </thead>
        <% @array = []
           @contador = 0
        %>
        <tbody>
        <% notifications.each_with_index do |notification, i| %>
            <% if notification.read %>
                <tr class="notification_read">
            <% else %>
                <tr>
            <% end %>
            <td style="padding-left: 3%;"><input type="checkbox" class="minimal" id="cb_notification"></td>
            <td><%= notification.sender.name %></td>
            <td><%= link_to notification.subject, notification, remote: true %></td>
            <td><%= t('activerecord.models.'+notification.table_type) %></td>
            <td>
              <%= link_to notification, method: :delete, data: { confirm: 'Tem certeza?', toggle: 'tooltip', placement: 'top', title: 'Apagar' } do %>
                  <i class="fa fa-trash btn btn-danger text-center" title="Apagar notificação"></i>
              <% end %>
            </td>
            </tr>
            <%= hidden_field_tag(('notification_id'), notification.id) %>

            <%
              @contador = @contador + 1
            %>
        <% end %>
        <%= hidden_field_tag(:pub_trash_input, "") %>
        <% @array = @array.to_json %>
        </tbody>
      </table>
      <!-- /.table -->
    </div>
    <!-- /.mail-box-messages -->
  </div>
  <!-- /.box-body -->
</div>
<!-- /. box -->

app/views/notifications/_notification.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><i class="fa fa-fw fa-eye"></i> Detalhes da notificação</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body no-padding">
    <div class="mailbox-read-info">
      <h3><strong><%= @notification.subject %></strong></h3>
      <h5><strong>From:</strong> <%= @notification.sender.name %> (<%= @notification.sender.email %>)
        <span class="mailbox-read-time pull-right">15 Feb. 2016 11:03 PM</span></h5>
    </div>
    <!-- /.mailbox-read-info -->
    <div class="mailbox-controls with-border text-center">

    </div>
    <!-- /.mailbox-controls -->
    <div class="mailbox-read-message">
      <p><%= @notification.description %></p>
      <br>
    </div>
    <!-- /.mailbox-read-message -->

  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <% unless @notification.is_response %>
        <%= link_to notifications_response_path(id: @notification.id, resp: true), data: {confirm: 'Tem certeza?'}, class: 'btn btn-success', method: 'post' do %>
            <i class="fa fa-check-square-o"></i> Aceitar troca
        <% end %>
        <%= link_to notifications_response_path(id: @notification.id, resp: false), data: {confirm: 'Tem certeza que deseja recusar?'}, class: 'btn btn-danger', method: 'post' do %>
            <i class="fa fa-close"></i> Recusar proposta
        <% end %>
    <% end %>
  </div>
  <!-- /.box-footer -->
</div>
<!-- /. box -->

app/views/notifications/index.html.erb
<% content_for :full_box do %>flag
<% end %>
<div class="row">
  <div class="col-md-3">
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Menu</h3>

        <div class="box-tools">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body no-padding">
        <ul class="nav nav-pills nav-stacked">
          <li class="active" id="li_index">
            <a id="notifications-index" href="#index"><i class="fa fa-inbox"></i> Não lidas
              <% if @notifications.where(read: false).size > 0 %>
                  <span class="label label-primary pull-right"><%= @notifications.where(read: false).size %></span>
              <% end %>
            </a></li>
          <li id="li_lidas"><a id="notifications-lidas" href="#notificacoeslidas"><i class="fa fa-envelope-open-o"></i> Lidas</a></li>
          <li id="li_enviadas"><a id="notifications-enviadas" href="#notificacoesenviadas"><i class="fa fa-upload"></i> Solicitações Enviadas</a></li>
          <li id="li_todas"><a id="notifications-todas" href="#todas"><i class="fa fa-trash-o"></i> Todas</a></li>
        </ul>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /. box -->
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Legenda</h3>

        <div class="box-tools">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body no-padding">
        <ul class="nav nav-pills nav-stacked">
          <li><label class="panel-heading"><i class="fa fa-circle-o text-red"></i> Tabela de retirada do lixo</label>
          </li>
          <li><label class="panel-heading"><i class="fa fa-circle-o text-yellow"></i> Tabela de alimentação</label></li>
          <li>
            <label class="panel-heading"><i class="fa fa-circle-o text-light-blue"></i> Tabela de limpeza das geladeiras</label>
          </li>
          <li>
            <label class="panel-heading"><i class="fa fa-circle-o text-green"></i> Tabela de limpeza da cozinha</label>
          </li>
        </ul>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
  <div id="notifications-content" class="col-md-9">
    <% if params[:q] %>
        <%= render 'notification', notification: @notification %>
    <% else %>
        <%= render 'list', notifications: @notifications.where(read: false) %>
    <% end %>
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->
<script>
    $(document).ready(function () {
        $('#notifications-index').click(function () {
            $('#notifications-content').html('<%= escape_javascript(render 'list', notifications: @notifications.where(read: false)) %>');
            window.history.replaceState({}, document.title, "/notifications");
            $('li[id^=li_]').removeClass('active');
            $('li[id$=li_index]').addClass('active');
        });
        $('#notifications-lidas').click(function () {
            $('#notifications-content').html('<%= escape_javascript(render 'list', notifications: @notifications.where(read: true)) %>');
            window.history.replaceState({}, document.title, "/notifications");
            $('li[id^=li_]').removeClass('active');
            $('li[id$=li_lidas]').addClass('active');
        });
        $('#notifications-enviadas').click(function () {
            $('#notifications-content').html('<%= escape_javascript(render 'list', notifications: sent_notifications ) %>');
            window.history.replaceState({}, document.title, "/notifications");
            $('li[id^=li_]').removeClass('active');
            $('li[id$=li_enviadas]').addClass('active');
        });
        $('#notifications-todas').click(function () {
            $('#notifications-content').html('<%= escape_javascript(render 'list', notifications: @notifications ) %>');
            window.history.replaceState({}, document.title, "/notifications");
            $('li[id^=li_]').removeClass('active');
            $('li[id$=li_todas]').addClass('active');
        });
    });
</script>

app/views/notifications/new.html.erb
<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<% content_for :full_box do %>flag<% end %>
<% content_for :notification do %>
<div class="row">
  <div class="col-md-12">
    <%= render 'notification', notification: @notification %>
  </div>
  <!-- /.col -->
</div>
<% end %>

app/views/notifications/show.js.erb
$('#notifications-content').html('<%= escape_javascript(render 'notification') %>');