config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :trashes
  get 'users/index'

  resources :rooms
  resources :courses
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  get 'users', to: 'users#index', as: 'users'
  post 'pub_trash', to: 'trashes#pub_trash', as: 'pub_trash'
  get 'pub_trash', to: 'trashes#pub_trash', as: 'published_trash'
  # get 'user/:id', to: 'users#show', as: 'user'
  # get 'user/edit/:id', to: 'users#edit', as: 'user_edit'

  resources :user, :controller => "users"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  # Home pages
  get 'home/tarefas', to: 'home#tarefas'

  # Swap tasks

  get '/trashes/swap/:id', to: 'trashes#swap_trash', as: 'swap_trash' # Swap trash
  get '/notifications/send/:id/:table', to: 'notifications#new', as: 'send_notification'
  get '/notifications/:id', to: 'notifications#show', as: 'notification'
  get '/notifications', to: 'notifications#index', as: 'notifications'
  post '/notifications', to: 'notifications#create'
  delete '/notifications/:id', to: 'notifications#destroy'
  post '/notifications/response', to: 'notifications#notification_response'
  get '/gerar_tabela', to: 'trashes#generate_trash_table', as: 'generate_trash_table'

end

app/views/shared/_action_links.html.erb
<%= link_to object, data: { toggle: 'tooltip', placement: 'top', title: 'Visualizar' } do %>
  <i class="fa fa-eye"></i>
<% end %>
&nbsp;
<%= link_to eval_with_rescue("edit_#{object.class.to_s.underscore}_path(#{object.id})"), data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
  <i class="fa fa-pencil text-yellow"></i>
<% end %>
&nbsp;
<%= link_to object, method: :delete, data: { confirm: 'Tem certeza?', toggle: 'tooltip', placement: 'top', title: 'Apagar' } do %>
  <i class="fa fa-trash text-red"></i>
<% end %>

app/views/shared/_aside.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MENU PRINCIPAL</li>
      <% if user_signed_in? %>
          <li <%= select_menu("home", "tarefas") %> >
            <%= link_to home_tarefas_path do %>
                <i class='fa fa-calendar fa-fw'></i> <span>Calendário de tarefas</span>
            <% end %>
          </li>
          <li <%= select_menu("rooms") %> >
            <%= link_to rooms_path do %>
                <i class='fa fa-bed fa-fw'></i> <span>Quartos</span>
            <% end %>
          </li>
          <li <%= select_menu("courses") %> >
            <%= link_to courses_path do %>
                <i class='fa fa-graduation-cap fa-fw'></i> <span>Cursos</span>
            <% end %>
          </li>
          <li <%= select_menu("users") %> >
            <%= link_to users_path do %>
                <i class='fa fa-users fa-fw'></i> <span>Residentes</span>
            <% end %>
          </li>

          <li class="treeview">
            <a href="#">
              <i class="fa fa-list fa-fw"></i><span>Tabelas</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li <%= select_menu("trashes") %> >
                <%= link_to trashes_path do %>
                    <i class='fa fa-trash fa-fw'></i> <span>Tabela de lixo</span>
                <% end %>
              </li>
              <li <%= select_menu("calendars") %> >
                <%= link_to calendars_path do %>
                    <i class='fa fa-calendar fa-fw'></i> <span>Calendário</span>
                <% end %>
              </li>
            </ul>
          </li>
      <% end -%>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <a target="_blank" href="http://www.ufpi.br" class="text-black"><b>TJPI</b></a>

  </div>
  <strong>Felipe de Sousa Silva</strong>
  <%= link_to "&copy;".html_safe %>
  2013-<%= Date.today.year %>
</footer>

app/views/shared/_form.html.erb
<%= content_for :full_box do %>opa<% end %>

<%= simple_form_for(object) do |f| %>
  <div class="box box-danger">
    <div class="box-header with-border">
      <h3 class="box-title">
        Dados do <%=t object.class.model_name.human %>
        <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
        <%= f.submit 'Salvar', class: 'btn btn-primary btn-xs' %>
      </h3>
    </div>
    <div class="box-body">
      <% (object.class.column_names - ['id', 'created_at', 'updated_at', 'deleted_at']).each do |column| %>
        <% if object.class.column_for_attribute(column).type == :text %>
          <%= f.input column, input_html: { rows: 10, cols: 20 } %>
        <% else %>
          <%= f.input column %>
        <% end %>
      <% end %>
    </div>
    <div class="box-footer">
      <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <%= link_to root_url, class: "logo" do %>
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>ReU</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Reuper </b>UFPI</span>
  <% end %>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
            <!-- Notifications: style can be found in dropdown.less -->
            <li class="dropdown notifications-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <% if current_user.notifications.where(read: false).size > 0 %>
                    <i class="fa fa-bell-o fa-fw" style="text-shadow: #00ff00;"></i>
                    <span class="label label-danger"><%= current_user.notifications.where(read: false).size %></span>
                <% else %>
                    <i class="fa fa-bell-o fa-fw"></i>
                <% end %>
              </a>
              <ul class="dropdown-menu">
                <%= render 'shared/notifications_menu' %>
              </ul>
            </li>
            <li class="dropdown user user-menu">
              <%= link_to "#", class: "dropdown-toggle", data: {toggle: 'dropdown'}, 'aria-expanded': 'true' do %>
                  <i class="fa fa-user-circle-o fa-lg"></i>
              <% end %>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                  <p>
                    <%= current_user.email %>
                    <small>Membro desde <%= l(current_user.created_at) %></small>
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-right">
                    <div class="col-md-6 col-xs-12">
                      <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-flat' do %>
                          <i class="fa fa-pencil"></i> Editar perfil
                      <% end %>
                    </div>
                    <div class="col-md-6 col-xs-12">
                      <%= link_to destroy_user_session_path, class: 'btn btn-danger btn-flat', method: "delete" do %>
                          <i class="fa fa-sign-out"></i> Sair
                      <% end %>
                    </div>
                  </div>
                </li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to new_user_registration_path, class: "linktjpi" do %>
                  Cadastrar-se
              <% end %>
            </li>
            <li>
              <%= link_to '/users/sign_in', class: "linktjpi" do %>
                  Entrar
              <% end %>
            </li>
        <% end %>
        <li>
          <%= link_to "http://www.ufpi.br", target: "_blank", class: "linktjpi" do %>
              UFPI
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_index.html.erb
<% exceptions ||= ['id', 'created_at', 'updated_at', 'deleted_at'] %>

<% if list.empty? %>
Sem dados cadastrados
<% else %>
<table class="table table-striped" >
  <thead>
    <tr>
      <th>ID</th>
      <% (list.first.class.column_names - exceptions).each do |column| %>
      <th><%= list.first.class.human_attribute_name(column) %></th>
      <% end %>
      <th width='90px'>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% list.each do |object| %>
    <tr>
      <td><%= link_to object.id, object %></td>
      <% (list.first.class.column_names - exceptions).each do |column| %>
      <td>
        <% if object.send(column).class == Date or
          object.send(column).class == DateTime or
          object.send(column).class == ActiveSupport::TimeWithZone or
          object.send(column).class == Time %>
          <%=l object.send(column) %>
          <% else %>
          <%= object.send(column) %>
          <% end %>
      </td>
      <% end %>
      <td>
        <%= render 'shared/action_links', object: object %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
    <%= will_paginate list, renderer: BootstrapPagination::Rails , :page_links => true%>
  </div>
</div>
<% end %>

app/views/shared/_notifications_menu.html.erb
<% me = current_user %>
<li class="header"><strong><%= t('activerecord.attributes.notification.count', count: me.notifications.where(read: false).count) %></strong></li>
<li>
  <!-- inner menu: contains the actual data -->
  <ul class="menu">
    <% me.notifications.where(read: false).each do |notification| %>
        <li>
          <%= link_to notifications_path(q: notification.id) do  %>
            <i class="fa fa-<%=notification.table_type %> text-yellow"></i> <%= notification.subject %>
          <% end %>
        </li>
    <% end %>
    <!--<li>-->
      <!--<a href="#">-->
        <!--<i class="fa fa-users text-red"></i> Fulano recusou sua solicitação de troca-->
      <!--</a>-->
    <!--</li>-->
    <!--<li>-->
      <!--<a href="#">-->
        <!--<i class="fa fa-shopping-cart text-green"></i> 25 sales made-->
      <!--</a>-->
    <!--</li>-->
  </ul>
</li>
<li class="footer"><a href="<%= notifications_path %>">Ver todas as notificações</a></li>

app/views/shared/_show.html.erb
<%= content_for :full_box do %>opa<% end %>

<div class="box box-danger">
  <div class="box-header with-border">
    <h3 class="box-title"><%=t object.class.model_name.human %></h3>
    <% if can? :edit, object %> <!--verificando se o usuario esta logado-->
      <%= link_to eval_with_rescue("edit_#{controller_name.singularize}_path(#{object.id})"), class: "btn btn-warning btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
        <i class="fa fa-pencil"></i> Editar
      <% end %>
    <% end %>
    <%= link_to 'Listagem', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
  </div>
  <div class="box-body no-padding">
    <table class="table table-bordered table-striped no-padding">
      <% (object.class.column_names - ['id', 'created_at', 'updated_at', 'deleted_at']).each do |column| %>
        <tr>
          <th width='15%'><%= object.class.human_attribute_name(column) %></th>
          <td>
            <% if object.send(column).class == Date or
              object.send(column).class == DateTime or
              object.send(column).class == ActiveSupport::TimeWithZone or
              object.send(column).class == Time %>
              <%=l object.send(column) %>
            <% else %>
              <%= object.send(column) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="box-footer">
    <% if can? :edit, object %> <!--verificando se o usuario esta logado-->
      <%= link_to eval_with_rescue("edit_#{controller_name.singularize}_path(#{object.id})"), class: "btn btn-warning", data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
        <i class="fa fa-pencil"></i> Editar
      <% end %>
    <% end %>

    <%= link_to 'Listagem', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>
  </div>
</div>

app/views/shared/_title.html.erb
<% unless controller_name == "registrations" or controller_name == "sessions" or controller_name == "notifications" %>
    <% value = "helpers.titles.#{action_name}" %>
    <% periodo_letivo = Calendar.where(is_holiday: false).last %>
    <h1>
      <% if action_name == "index" %>
          <i class="fa fa-fw fa-list"></i>
      <% elsif action_name == "show" %>
          <i class="fa fa-fw fa-eye"></i>
      <% elsif action_name == "new" %>
          <i class="fa fa-fw fa-edit"></i>
      <% elsif action_name == "edit" %>
          <i class="fa fa-fw fa-pencil"></i>
      <% else %>
          <i class="fa fa-fw fa-question-circle"></i>
      <% end -%>


      <%= t value %>
      <% if action_name == "index" %>
          <%= t 'of' %> <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human.downcase.pluralize %>
      <% else %>
          <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human.downcase %>
      <% end -%>
      <% unless controller_name == 'calendars' %>
          <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human.pluralize %></small>
      <% else %>
          <small class="label-default label">
            <i class="fa fa-calendar fa-fw"></i>
            <% if periodo_letivo %>
                Período letivo: <%= l(periodo_letivo.inicio_semestre) %> - <%= l(periodo_letivo.fim_semestre) %>
            <% else %>
                <% if current_user %>
                    <% if current_user.has_role? :admin %>
                        <%= link_to 'Definir período letivo', new_calendar_path(is_holiday: false), class: 'btn-flat' %>
                    <% end %>
                <% end %>
            <% end %>
          </small>
      <% end %>
      <% if can? :new, controller_name.singularize %>
          <% unless action_name == 'new' || controller_name == 'users' || controller_name == 'calendars' %>
              <%= link_to "#{controller_name}/new", class: "btn btn-primary btn-xs" do %>
                  <%= t('.new', default: t("helpers.links.new")) %> <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human %>
                  <i class='fa fa-plus'></i>
              <% end %>
          <% end %>
      <% end %>
    </h1>
<% end -%>