config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :trashes
  get 'users/index'

  resources :rooms
  resources :courses
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  get 'users', to: 'users#index', as: 'users'
  post 'pub_trash', to: 'trashes#pub_trash', as: 'pub_trash'
  get 'pub_trash', to: 'trashes#pub_trash', as: 'published_trash'
  # get 'user/:id', to: 'users#show', as: 'user'
  # get 'user/edit/:id', to: 'users#edit', as: 'user_edit'

  resources :user, :controller => "users"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  # Home pages
  get 'home/tarefas', to: 'home#tarefas'

  # Swap tasks

  get '/trashes/swap/:id', to: 'trashes#swap_trash', as: 'swap_trash' # Swap trash
  get '/notifications/send/:id/:table', to: 'notifications#new', as: 'send_notification'
  get '/notifications/:id', to: 'notifications#show', as: 'notification'
  get '/notifications', to: 'notifications#index', as: 'notifications'
  post '/notifications', to: 'notifications#create'
  delete '/notifications/:id', to: 'notifications#destroy'
  post '/notifications/response', to: 'notifications#notification_response'
  get '/gerar_tabela', to: 'trashes#generate_trash_table', as: 'generate_trash_table'

end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_paper_trail
  acts_as_paranoid

  def tables
    tables = []
    if self.trash
      tables << 'Retirada de lixo'
    end
    if self.food
      tables << 'Alimentação'
    end
    if self.fridge
      tables << 'Limpeza das geladeiras'
    end
    if self.kitchen
      tables << 'Limpeza da cozinha'
    end
    tables
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :set_paper_trail_whodunnit

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
    @calendar.is_holiday = params[:is_holiday]
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:is_holiday, :date, :inicio_semestre, :fim_semestre, :trash, :food, :fridge, :kitchen)
    end
end

app/views/calendars/_form.html.erb
<%= content_for :full_box do %>opa
<% end %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= @calendar.is_holiday ? 'Adicionar data' : 'Definir Período letivo' %></h3>
  </div>
  <div class="box-body">
    <!-- Date -->
    <%= simple_form_for(@calendar) do |f| %>
        <%= f.error_notification %>
        <% if @calendar.is_holiday %>
            <div class="form-group">
              <label>Data:</label>
              <div class="input-group date col-md-6">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <input type="text" class="form-control pull-right" id="datepicker">
                <%= f.input :date, id: :date, as: :hidden %>
                <%= f.input :is_holiday, id: :is_holiday, as: :hidden, value: true %>
              </div>
              <!-- /.input group -->
              <br>
              <label>
                Selecione a(s) tabela(s):
              </label>
              <div class="input-group col-md-6 col-lg-6 col-xs-12 form-inline">
                <%= f.input :trash, id: :trash, input_html: {class: 'minimal'} %>
                &nbsp;
                <%= f.input :food, id: :food, input_html: {class: 'minimal'} %>
                &nbsp;
                <%= f.input :kitchen, id: :kitchen, input_html: {class: 'minimal'} %>
                &nbsp;
                <%= f.input :fridge, id: :fridge, input_html: {class: 'minimal'} %>
              </div>
            </div>
            <!-- /.form group -->
        <% else %>
            <!-- Date range -->
            <div class="form-group">
              <label>Período letivo:</label>

              <div class="input-group col-md-6">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <input type="text" class="form-control pull-right" id="reservation">
                <%= f.input :inicio_semestre, id: :inicio_semestre, as: :hidden %>
                <%= f.input :fim_semestre, id: :fim_semestre, as: :hidden %>
                <%= f.input :is_holiday, id: :is_holiday, as: :hidden, value: false %>
              </div>
              <!-- /.input group -->
            </div>
        <% end %>
        <!-- /.form group -->
        <div class="form-actions col-xs-12">
          <%= f.button :submit, id: 'save_date' %>
        </div>
    <% end %>
  </div>
  <!-- /.box-body -->
</div>

app/views/calendars/edit.html.erb
<%= render 'form', calendar: @calendar %>
<%= link_to 'Voltar', calendars_path %>

app/views/calendars/index.html.erb
<%= content_for :full_box do %>flag
<% end %>
<div class="box box-primary">
  <div class="box-header with-border">
    <h5 class="box-title">
      Datas onde não haverá tarefa em uma ou mais tabelas específicas
    </h5>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="col-md-12">
        <table id="datatable" class="table table-striped table-bordered datatables2">
          <thead>
          <tr>
            <th>Data</th>
            <th>Aplica-se às tabelas</th>
            <th>Adicionado em</th>
            <th>Última alteração</th>
            <th><%= t '.actions', :default => t("helpers.actions") %></th>
          </tr>
          </thead>
          <tbody>
          <% @calendars.each do |calendar| %>
              <% if calendar.is_holiday %>
                  <tr>
                    <td><%= link_to l(calendar.date), calendar_path(calendar) %></td>
                    <td>
                      <% calendar.tables.each_with_index do |k, i| %>
                            <%= k %><br>
                      <% end %>
                    </td>
                    <td><%= l(calendar.created_at, format: :short) %></td>
                    <td><%= l(calendar.updated_at, format: :short) %></td>
                    <td>
                      <%= link_to calendar, :class => 'btn btn-primary btn-xs', data: {toggle: 'tooltip', placement: 'top', title: 'Ver perfil completo'} do %>
                          <i class="fa fa-eye fa-fw"></i>
                      <% end %>
                      <% if current_user %>
                          <% if current_user.has_role? :admin %>
                              <%= link_to edit_calendar_path(calendar), :class => 'btn btn-warning btn-xs', data: {toggle: 'tooltip', placement: 'top', title: 'Editar feriado'} do %>
                                  <i class="fa fa-pencil fa-fw"></i>
                              <% end %>
                              <%= link_to calendar, method: :delete, :class => 'btn btn-danger btn-xs', data: {confirm: 'Tem certeza?', toggle: 'tooltip', placement: 'top', title: 'Remover feriado'} do %>
                                  <i class="fa fa-trash fa-fw"></i>
                              <% end %>
                          <% end %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% if current_user %>
      <% if current_user.has_role? :admin %>
          <div class="box-footer">
            <div class="col-xs-12 col-md-2">
              <%= link_to 'Registrar uma data', new_calendar_path(is_holiday: true), class: 'btn btn-flat btn-primary col-xs-12 col-md-12' %>
            </div>
            &nbsp
            <div class="col-xs-12 col-md-2">
              <% if Calendar.where(is_holiday: false).count == 0 %>
                <%= link_to 'Cadastrar período letivo', new_calendar_path(is_holiday: false), class: 'btn btn-flat btn-info col-xs-12 col-md-12' %>
              <% else %>
                  <%= link_to 'Alterar período letivo', edit_calendar_path(Calendar.where(is_holiday: false).last), class: 'btn btn-flat btn-warning col-xs-12 col-md-12' %>
              <% end %>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/calendars/new.html.erb
<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered datatables2">
      <thead>
      <tr>
        <th>Data</th>
        <th>Aplica-se às tabelas</th>
        <th>Adicionado em</th>
        <th>Última alteração em</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>
          <%= @calendar.is_holiday ? l(@calendar.date) : ("Período letivo: " + l(@calendar.inicio_semestre).to_s + " - " + l(@calendar.fim_semestre).to_s) %>
        </td>
        <td>
          <% @calendar.tables.each_with_index do |k, i| %>
              <%= k %><br>
          <% end %>
        </td>
        <td>
          <%= l(@calendar.created_at, format: :short) %>
        </td>
        <td>
          <%= l(@calendar.updated_at, format: :short) %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>