config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :trashes
  get 'users/index'

  resources :rooms
  resources :courses
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  get 'users', to: 'users#index', as: 'users'
  post 'pub_trash', to: 'trashes#pub_trash', as: 'pub_trash'
  get 'pub_trash', to: 'trashes#pub_trash', as: 'published_trash'
  # get 'user/:id', to: 'users#show', as: 'user'
  # get 'user/edit/:id', to: 'users#edit', as: 'user_edit'

  resources :user, :controller => "users"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
  # Home pages
  get 'home/tarefas', to: 'home#tarefas'

  # Swap tasks

  get '/trashes/swap/:id', to: 'trashes#swap_trash', as: 'swap_trash' # Swap trash
  get '/notifications/send/:id/:table', to: 'notifications#new', as: 'send_notification'
  get '/notifications/:id', to: 'notifications#show', as: 'notification'
  get '/notifications', to: 'notifications#index', as: 'notifications'
  post '/notifications', to: 'notifications#create'
  delete '/notifications/:id', to: 'notifications#destroy'
  post '/notifications/response', to: 'notifications#notification_response'
  get '/gerar_tabela', to: 'trashes#generate_trash_table', as: 'generate_trash_table'

end

app/models/room.rb
class Room < ApplicationRecord
  validates :number, :floor, presence: true
  has_paper_trail
  acts_as_paranoid

  has_many :users

  def room
    self.number.to_s + '/' + self.floor.to_s
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => [:show, :index]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_paper_trail_whodunnit

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @pesquisa = params[:pesquisa]

    if @pesquisa.present?
      where_target = '%' << params[:pesquisa] << '%'
      @rooms = @rooms.where('rooms.number ILIKE ? OR
        rooms.floor ILIKE ?', where_target, where_target)
    end

    @rooms = @rooms.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html {redirect_to @room, notice: 'Room was successfully created.'}
        format.json {render :show, status: :created, location: @room}
      else
        format.html {render :new}
        format.json {render json: @room.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html {redirect_to @room, notice: 'Room was successfully updated.'}
        format.json {render :show, status: :ok, location: @room}
      else
        format.html {render :edit}
        format.json {render json: @room.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html {redirect_to rooms_url, notice: 'Room was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:number, :floor)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= content_for :full_box do %>flag<% end %>

<%= simple_form_for @room do |f| %>
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">
          Dados do <%=t @room.class.model_name.human %>
          <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default btn-xs" %>
          <%= f.submit 'Salvar', class: 'btn btn-primary btn-xs' %>
        </h3>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-12">
            <%= f.label :number %>
            <%= f.select :number, [*1...16], {include_blank: false} , { class: 'chosen-select' } %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-12">
            <%= f.label :floor %>
            <%= f.select :floor, [['Térreo', 'Piso superior'], @room.floor], {include_blank: false} , { class: 'chosen-select' } %>
          </div>
        </div>
      </div>
      <div class="box-footer">
        <%= link_to 'Cancelar', eval_with_rescue("#{controller_name}_path"), class: "btn btn-default" %>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<%= render :partial => 'form', @room => @room %>

app/views/rooms/index.html.erb
<div class="row">
  <%= simple_form_for rooms_path, method: "get" do |f| %>
      <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
        <%= f.input :pesquisa, input_html: {value: params[:pesquisa], name: 'pesquisa', placeholder: "Pesquise por piso ou número", id: "pesquisa"}, label: false  %>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
        <%= f.submit "Pesquisar", class: "btn btn-default btn-block" %>
      </div>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th class='text-center'>Number</th>
      <th class='text-center'>Floor</th>
      <th class='text-center' width="150px"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td class='text-center'><%= room.number %></td>
        <td class='text-center'><%= room.floor %></td>
        <td class='text-center'>
          <%= render 'shared/action_links', object: room %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
    <%= will_paginate @room, renderer: BootstrapPagination::Rails , :page_links => true%>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%= content_for :full_box do %>flag<% end %>
<div class="box box-default">
  <div class="box-body">
    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Number:</strong>
          <%= @room.number %>
        </p>

        <p>
          <strong>Floor:</strong>
          <%= @room.floor %>
        </p>

      </div>
    </div>
  </div>
</div>
<% @users = User.where(room: @room) %>
<div class="box box-default">
  <div class="box-body">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped table-bordered datatables2">
          <thead>
          <h4>Residentes do quarto <strong><%= @room.room %> </strong></h4>
          <tr>
            <th>Nome</th>
            <th>Curso</th>
            <th>Quarto</th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= link_to user.course.name, course_path(user.course.id) %></td>
                <td><%= link_to user.room.room, room_path(user.room.id) %></td>
                <td>
                  <%= link_to user, :class => 'btn btn-primary btn-xs', data: { toggle: 'tooltip', placement: 'top', title: 'Ver perfil completo' } do %>
                      <i class="fa fa-eye fa-fw"></i>
                  <% end %>
                  <% if current_user %>
                      <% if current_user.has_role? :admin %>
                          <%= link_to  edit_user_path(user), :class => 'btn btn-warning btn-xs', data: { toggle: 'tooltip', placement: 'top', title: 'Alterar Perfil' } do %>
                              <i class="fa fa-pencil fa-fw"></i>
                          <% end %>
                      <% end %>
                  <% end %>

                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>